apiVersion: v1
kind: Service
metadata:
  name: {{ template "redash.fullname" . }}-{{ .Values.server.service.name }}
  labels:
    app: {{ template "redash.name" . }}-redash-server
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
  - name: {{ .Release.Name }}-redash-{{ .Values.server.service.name }}
    port: {{ .Values.server.service.externalPort }}
    targetPort: {{ .Values.server.service.internalPort }}
  selector:
    io.redash.service: {{ .Release.Name }}-redash-server
    app: {{ template "redash.name" . }}
    release: {{ .Release.Name }}
  {{- if .Values.server.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.server.service.loadBalancerIP }}
  {{- end }}
