{{- if .Values.configmap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "scrapyd.fullname" . }}
data:
{{- range $key, $val := .Values.configmap }}
  {{ $key }}: |-
{{ $val | indent 4}}
{{- end }}
{{- end -}}
