apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-redash-server-configmap
data:
  REDASH_COOKIE_SECRET: {{ randAlphaNum 10 | b64enc | quote }}
  REDASH_WEB_WORKERS: {{ .Values.server.configMap.redashWebWorkers | quote }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-redash-worker-configmap
data:
  QUEUES: {{ .Values.server.configMap.queue | quote }}
  WORKERS_COUNT: {{ .Values.worker.configMap.workerCount | quote }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-redash-common-configmap
data:
{{ toYaml .Values.common.configMap | indent 2 }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-redash-flower-configmap
data:
  CELERY_BROKER_URL: {{ .Values.flower.configMap.celeryBrokerUrl | quote }}
