
{{- if and .Values.db.persistence.enabled (not .Values.db.persistence.existingClaim) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "redash.fullname" . }}
  labels:
    app: {{ template "redash.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- if .Values.db.persistence.annotations }}
  annotations:
{{ toYaml .Values.db.persistence.annotations | indent 4 }}
{{- end }}
spec:
  accessModes:
    - {{ .Values.db.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.db.persistence.size | quote }}
{{- if .Values.db.persistence.storageClass }}
{{- if (eq "-" .Values.db.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.db.persistence.storageClass }}"
{{- end }}
{{- end }}
{{- end -}}