apiVersion: v1
kind: Secret
metadata:
  name: {{ template "redash.fullname" . }}
  labels:
    app: {{ template "redash.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  REDASH_DATABASE_URL: {{ template "redash.databaseurl" . }}


---

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "redash.fullname" . }}-db
  labels:
    app: {{ template "redash.fullname" . }}-db
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if .Values.db.meta.pass }}
  postgres-password:  {{ .Values.db.meta.pass | b64enc | quote }}
  {{ else }}
  postgres-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
