{{- if .Values.flower.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "redash.name" . }}-{{ .Values.flower.deployment.name }}
  labels:
    app: {{ template "redash.name" . }}-{{ .Values.flower.deployment.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.flower.deployment.replicas }}
  template:
    metadata:
      labels:
        io.redash.service: {{ .Release.Name }}-{{ .Values.flower.deployment.name }}-redash
        app: {{ template "redash.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: flower
          image: "{{ .Values.flower.deployment.image.repository }}:{{ .Values.flower.deployment.image.tag }}"
          command: ["flower", "--port={{ .Values.flower.service.internalPort }}", "--address=0.0.0.0"]
          ports:
          - containerPort: {{ .Values.flower.service.internalPort }}
            protocol: TCP
          envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-redash-flower-configmap
          resources:
{{ toYaml .Values.flower.deployment.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.flower.deployment.nodeSelector | indent 8 }}
    {{- end }}
{{- end }}
