apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "redash.name" . }}-redash-scheduler
  labels:
    app: {{ template "redash.name" . }}-scheduler
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.scheduler.replicas }}
  template:
    metadata:
      labels:
        io.redash.service: {{ .Release.Name }}-redash-scheduler
        app: {{ template "redash.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: scheduler
          image: "{{ .Values.base.deployment.image.repository }}:{{ .Values.base.deployment.image.tag }}"
          args: ["scheduler"]
          env:
          - name: REDASH_DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: {{ template "redash.fullname" . }}
                key: REDASH_DATABASE_URL
          - name: REDASH_REDIS_URL
            value: "redis://{{ .Release.Name }}-{{ template "redash.name" . }}-{{ .Values.broker.deployment.name }}:6379/0"
          envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-redash-common-configmap
          resources:
{{ toYaml .Values.scheduler.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.scheduler.nodeSelector | indent 8 }}
    {{- end }}
