apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "redash.name" . }}-{{ .Values.server.deployment.name }}
  labels:
    app: {{ template "redash.name" . }}-{{ .Values.server.deployment.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.server.deployment.replicas }}
  template:
    metadata:
      labels:
        io.redash.service: {{ .Release.Name }}-{{ .Values.server.deployment.name }}-redash
        app: {{ template "redash.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: server
          image: "{{ .Values.server.deployment.image.repository }}:{{ .Values.server.deployment.image.tag }}"
          args: ["server"]
          ports:
          - containerPort: {{ .Values.server.service.internalPort }}
            protocol: TCP
          env:
          - name: REDASH_DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: {{ template "redash.fullname" . }}
                key: REDASH_DATABASE_URL
          - name: REDASH_REDIS_URL
            value: "redis://{{ .Release.Name }}-{{ template "redash.name" . }}-{{ .Values.broker.deployment.name }}:6379/0"
          envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-redash-server-configmap
          - configMapRef:
              name: {{ .Release.Name }}-redash-common-configmap
          resources:
{{ toYaml .Values.server.deployment.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.server.deployment.nodeSelector | indent 8 }}
    {{- end }}
