apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "redash.name" . }}-redash-worker
  labels:
    app: {{ template "redash.name" . }}-worker
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.worker.replicas }}
  template:
    metadata:
      labels:
        io.redash.service: {{ .Release.Name }}-redash-worker
        app: {{ template "redash.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: worker
          image: "{{ .Values.base.deployment.image.repository }}:{{ .Values.base.deployment.image.tag }}"
          args: ["worker"]
          env:
          - name: REDASH_DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: {{ template "redash.fullname" . }}
                key: REDASH_DATABASE_URL
          - name: REDASH_REDIS_URL
            value: "redis://{{ .Release.Name }}-{{ template "redash.name" . }}-{{ .Values.broker.deployment.name }}:6379/0"
          envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-redash-worker-configmap
          - configMapRef:
              name: {{ .Release.Name }}-redash-common-configmap
          resources:
{{ toYaml .Values.worker.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.worker.nodeSelector | indent 8 }}
    {{- end }}
